List<String> images = [
  'https://images.mid-day.com/images/images/2021/apr/Anubhav-Mukherjee_d.jpg',
  'https://youthincmag.com/wp-content/uploads/2018/06/yogesh-chabria.jpg',
  'https://images.assettype.com/fortuneindia%2F2022-02%2F6d7aa851-bebf-4e86-b6c9-4ab7e4521e3c%2FWhatsApp_Image_2022_02_24_at_14_58_47.jpeg?w=960&q=95',
  'https://data1.ibtimes.co.in/en/full/746075/sudhanshu-kumar.jpg',
  'https://www.iwmbuzz.com/wp-content/uploads/2019/02/das.jpg',
  'https://pbs.twimg.com/profile_images/1334033432523882496/egIURxxk_400x400.jpg',
  'https://pbs.twimg.com/profile_images/1367348687609896961/ib_AHkdl_400x400.jpg',
  'https://www.naukri.com/blog/content/images/2019/03/saurabh-jain-paytm-vp-new.jpeg',
  'https://images.indulgexpress.com/uploads/user/imagelibrary/2021/12/23/original/SayanChakraborty.jpeg?w=400&dpr=2.6',
  'https://miro.medium.com/fit/c/176/176/1*Fh5vwiERC5tOG4UMqoHGiA.jpeg',
  'https://i.ytimg.com/vi/tuXSCa9fvvs/maxresdefault.jpg',
  'https://firebasestorage.googleapis.com/v0/b/envisage-22.appspot.com/o/E-talk%2FArijit%20hajra.png?alt=media&token=0d60ddfa-ea02-4cef-9877-142bbe80d5fd',
  'https://sourcinghardware.net/wp-content/uploads/2019/01/jacks-Pic-1-1024x643.jpg',
  'https://images.livemint.com/img/2019/07/14/600x338/beb1f748-a62c-11e9-975b-46f21599486e_1563125944432_1563126020785.jpg',
  'https://www.f6s.com/content-resource/profiles/2416849_original.jpg',
  'https://i.ytimg.com/vi/qXOGQGLXbjo/maxresdefault.jpg',
  'https://medias.freeflow.zone/wp-content/uploads/2020/06/28233429/Aaquib-Hussain_bw_web.jpg',
  'https://bjym.org/wp-content/uploads/2021/09/image18-530x526.jpeg',
  'https://faces.grantthornton.in/images/Sujay-Santra-390x390.jpg',
  'https://upload.wikimedia.org/wikipedia/commons/b/b8/Amitabha_Singh.jpg',
  'https://spiderimg.amarujala.com/assets/images/2018/05/16/750x506/maya-vishwakarma_1526461507.jpeg',
  'https://circuitdigest.com/sites/default/files/field/image/Gautham-Pasupuleti-CEO-Biodesign-Innovation-Lab.jpg',
  'https://static.toiimg.com/thumb/msid-78719256,width-1200,height-900,resizemode-4/.jpg',
  'https://circuitdigest.com/sites/default/files/field/image/Gautham-Pasupuleti-CEO-Biodesign-Innovation-Lab.jpg',
  'https://static.toiimg.com/thumb/msid-78719256,width-1200,height-900,resizemode-4/.jpg',
];

List<String> names = [
  'Anubhav Mukherjee',
  'Yogesh Chabria',
  'Sumit Agarwal',
  'Sudhanshu Kumar',
  'Aritra Das',
  'Manish Kumar Saraf ',
  'Arpan Pal',
  'Saurabh Jain',
  'Sayan Chakraborty',
  'Dr. Amiya Patanaik',
  'Rostam J. Neuwirth',
  'Arijit Hajra',
  'Jack Sim',
  'Anil Joshi',
  'Satadru Chowdhury',
  'Sanjeev Sharma',
  'Aaquib Hussain',
  'Varun Jhaveri',
  'Sujay Santra',
  'Amitabha Singh',
  'Maya Vishwakarma',
  'Gautham Pasupuleti',
  'Rahul Basak',
  'Gautham Pasupuleti',
  'Rahul Basak',
];

List<String> designation = [
  'CEO of The kolkata Buzz',
  'Founder of The Happionaire Way',
  'Founder of The PR Signal',
  'Founder of iNeuron & CEO of iNeuron.ai',
  'Owner of Assorted Motion Pictures Pvt. Ltd.',
  'Health and Performance Specialist',
  'Distinguished Chief Scientist and Research Area Head at TCS',
  'Ex- Vice President – Paytm',
  'Founder of Where’s The Food',
  'Neurobit Technologies – CEO & Co-Founder',
  'Global Legal Studies at University of Macau, HOD',
  'Founder & CEO at Think Again Lab',
  'Founder – World Toilet Organisation',
  'Managing Partner at Unicorn India Ventures',
  'Founder – Vaanahaa Education & Innovation Labs',
  'CEO/CTO at Swaayatt Robots',
  'Founding Partner at Mindspace Ventures(Freeflow)',
  'Leading Innovation Strategist at NHA',
  'Founder & CEO – Ikure Techsoft Pvt. Ltd.',
  'Director & Independent Filmmaker',
  'PadWoman of India – Founder Sukarma',
  'CEO & MD- Biodesign Innovation Labs',
  'CEO & CO-Founder – Amar Canvas',
  'CEO & MD- Biodesign Innovation Labs',
  'CEO & CO-Founder – Amar Canvas',
];

